import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Transition from "./Transition";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Drones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={inter.className + " h-[5000px]"}>
      <Transition>{children}</Transition>
        </body>
    </html>
  );
}
